version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - type:maintenance
    commit-message:
      prefix: chore
      include: scope
    groups:
      npm-development-dependencies:
        dependency-type: development
      npm-production-dependencies:
        dependency-type: production

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
      - type:maintenance
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
